In [1]:
import numpy as np

x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [2]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [3]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [6]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])