In [7]:
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
X[2, [2, 0, 1]] #fancy and simple indexing

array([10,  8,  9])

In [4]:
X[1:, [2, 0, 1]] #fancy with slicing

array([[ 6,  4,  5],
       [10,  8,  9]])

In [9]:
mask = np.array([1, 0, 1, 0], dtype=bool) #fancy with mask
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])