In [21]:
import numpy as np
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [22]:
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [23]:
x = np.zeros(10)
x[[0, 0]] = [4, 6] #where the 4 go?

print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
i = [2, 3, 3, 4, 4, 4]

x[i] += 1

print(x)

[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]


In [25]:
x = np.zeros(10)
np.add.at(x, i, 1)

print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]
