In [11]:
import numpy as np

def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        print(x[1:])
        np.random.shuffle(x)
         
    return x

In [12]:
x = np.array([2, 1, 4, 3, 5])

bogosort(x)

[1 4 3 5]
[1 5 3 2]
[4 3 2 5]
[3 5 2 1]
[3 4 2 1]
[1 2 4 3]
[4 5 3 1]


array([1, 2, 3, 4, 5])