In [9]:
#Broadcasting example 1

import numpy as np

M = np.ones((2, 3)) #shape (2,3) 2D

a = np.arange(3) #shape (3,) 1D

#Force a dimension to match the shape of M a.shape -> (2, 3)

M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [10]:
#Broadcasting example 2

a = np.arange(3).reshape((3, 1)) #shape (3, 1) 2D

b = np.arange(3) #shape (3,) 1D

#Pad the shape of b with ones b.shape -> (1, 3)

#Upgrade each of these ones to match the corresponding size of the other array
# a.shape = (3, 3), b.shape = (3, 3)

a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [11]:
#Broadcasting example 3

M = np.ones((3, 2)) #shape (3, 2)
a = np.arange(3) #shape (3, )

#Pad the shape of a with ones a.shape -> (1, 3)
# the first dimension of a is stretched to match that of b
# M.shape = (3, 2), a.shape = (3, 3)

M + a


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [12]:
a[:, np.newaxis].shape

(3, 1)

In [13]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [14]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])