In [1]:
import numpy as np

tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])

In [3]:
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
