In [2]:
import numpy as np

M = np.random.random((3, 4))
print(M)

[[0.20721354 0.80744909 0.14305007 0.02149152]
 [0.22511982 0.07432063 0.16708877 0.85883988]
 [0.00880863 0.35944198 0.39514291 0.42044028]]


In [3]:
M.sum()

np.float64(3.6884071162841825)

In [4]:
M.min(axis=0) #column

array([0.00880863, 0.07432063, 0.14305007, 0.02149152])

In [5]:
M.min(axis=1) #row

array([0.02149152, 0.07432063, 0.00880863])