In [1]:
import numpy as np

rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))


In [2]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [6]:
#count entries

print(np.count_nonzero(x < 6))

8


In [4]:
print(np.sum(x < 6))

8


In [5]:
#this sumation can be done along rows or columns

print(np.sum(x < 6, axis=1))
print(np.sum(x < 6, axis=0))

[4 2 2]
[2 2 2 2]


In [7]:
# are thera any values greater than 8
np.any( x > 8)

np.True_

In [10]:
# are thera any values less than zero
np.any(x < 0)

np.False_

In [11]:
# are all values less than 10

print(np.all(x < 10))

True


In [13]:
# are all values along each row greater than 8
np.all(x < 8, axis=1)

array([ True, False,  True])