In [1]:
import numpy as np
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [2]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [3]:
x[x < 5] #reruned values positions

array([0, 3, 3, 3, 2, 4], dtype=int32)

In [16]:
import pandas as pd

#use pandas to extract rainfall inches as a NUmp array
rainfall = pd.read_csv('./Seattle2014.csv')['PRCP'].values
inches = rainfall / 254 # 1/10 -> inches
inches.shape #365 values

(365,)

In [26]:
rainy = (inches > 0)

#construct a mask of all sumer days (June 21 st is the 172nd day)

summer = (np.arange(365) - 172 < 90) & (np.arange(365) - 172 > 0)

print("Median precipt on rainy days in 2014 (inches):", np.median(inches[rainy]))
print("Median precipt on summer days:", np.median(inches[summer]))
print("Maximun precipt onsummer days in 2014 (inches):", np.max(inches[summer]))
print("Median precipt on non-summer rainy days:", np.median(inches[rainy & ~summer]))


Median precipt on rainy days in 2014 (inches): 0.19488188976377951
Median precipt on summer days: 0.0
Maximun precipt onsummer days in 2014 (inches): 0.8503937007874016
Median precipt on non-summer rainy days: 0.20078740157480315


In [24]:
inches[summer]

array([0.        , 0.        , 0.        , 0.        , 0.07086614,
       0.09055118, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.01181102,
       0.75984252, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01968504, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.01968504,
       0.5       , 0.8503937 , 0.        , 0.03937008, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.33070866, 0.0511811 ,
       0.        , 0.11811024, 0.        , 0.        , 0.     