In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [2]:
x > 3

array([False, False, False,  True,  True])

In [3]:
x != 1

array([False,  True,  True,  True,  True])

In [4]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [6]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [7]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])