In [2]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


In [3]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [4]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))


[ 1  2  3  4  5  6 99 99 99]


In [6]:
grid = np.array([[1, 2, 3 ],
                 [4, 5, 6]])

In [9]:
#concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
#concatenate along the second axis
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

#vstack vertically stack arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [12]:
y = np.array([[99],
              [99]])

#hstack horizontally stack arrays

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [13]:
#spliting of arrays
x = [1,2,3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])

print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [15]:
grid = np.arange(16).reshape(4, 4)

In [16]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [17]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
