In [ ]:
#One dimensional subarrays
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
x[:5]

array([0, 1, 2, 3, 4])

In [3]:
x[5:]

array([5, 6, 7, 8, 9])

In [4]:
x[4:7]

array([4, 5, 6])

In [5]:
x[::2] #every other element


array([0, 2, 4, 6, 8])

In [6]:
x[1::2]

array([1, 3, 5, 7, 9])

In [7]:
x[::-1] #all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [20]:
#multi-dimensional subarrays
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4)) #2D
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [13]:
x2[:2, :3] #two files three columns

array([[5, 0, 3],
       [7, 9, 3]], dtype=int32)

In [15]:
x2[:3, ::2] #all rows, every other columns

array([[5, 3],
       [7, 3],
       [2, 7]], dtype=int32)

In [11]:
x2[::-1, ::-1] #reversed all

array([[6, 7, 4, 2],
       [5, 3, 9, 7],
       [3, 3, 0, 5]], dtype=int32)

In [16]:
print(x2[:, 0]) #first column of x2

[5 7 2]


In [17]:
print(x2[0, :]) #first row of x2

[5 0 3 3]


In [18]:
print(x2[0])

[5 0 3 3]


In [23]:
#subarrays as no-copy views
x2_sub = x2[:2,:2]
print(x2_sub)

[[5 0]
 [7 9]]


In [25]:
x2_sub[0, 0] = 99

print("x2_sub modified:", x2_sub)

x2_sub modified: [[99  0]
 [ 7  9]]


In [26]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [27]:
#creating copies of a array
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [ 7  9]]


In [28]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  0]
 [ 7  9]]


In [29]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]
