In [2]:
import numpy as np

np.random.seed(0)

x1 = np.random.randint(10, size=6) #1D
x2 = np.random.randint(10, size=(3, 4)) #2D
x3 = np.random.randint(10, size=(3, 4, 5)) #3D

In [6]:
x1


array([5, 0, 3, 3, 7, 9], dtype=int32)

In [7]:
x1[0]

np.int32(5)

In [8]:
x1[4]

np.int32(7)

In [9]:
x1[-1]

np.int32(9)

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [11]:
x2[0,0]

np.int32(3)

In [12]:
x2[2,0]

np.int32(1)

In [13]:
x2[2, -1]

np.int32(7)

In [14]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [15]:
x1[0] = 3.14159 #will be truncated
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)