In [7]:
import numpy as np
#create a legth-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
#create a 3*5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#create a 3*5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#create an array of five values between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
#array 3*3 of uniformly values
np.random.random((3,3))

array([[0.5965809 , 0.2492315 , 0.33808386],
       [0.6894714 , 0.51538089, 0.73432593],
       [0.41633195, 0.47793137, 0.78050596]])

In [23]:
np.random.randint(0, 10, (3,3))

array([[4, 4, 9],
       [2, 6, 3],
       [8, 3, 7]], dtype=int32)

In [15]:
np.random.normal(0, 1, (3, 3))

array([[ 0.16540518, -1.63504878, -0.05572338],
       [ 1.7939625 ,  1.2717706 ,  0.512783  ],
       [ 0.30804871, -1.61912078, -0.59774684]])

In [24]:
#idenity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#uninitialized array of tree integers
np.empty(3)

array([1., 1., 1.])