In [1]:
import numpy as np
grid = np.arange(1, 10).reshape((3, 3))
print (grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
x = np.array([1, 2, 3])

#row vector via reshape

row_vector = x.reshape((1, 3))
print(row_vector)

[[1 2 3]]


In [3]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [4]:
#column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [5]:
#column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])