In [2]:
import numpy as np

np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    
    for i in range (len(values)):
        output[i] = 1.0 / values[i]
    
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [7]:
big_array = np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

2.06 s ± 135 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
#Introducing UFuncs
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [11]:
%timeit (1.0 / big_array)

3.42 ms ± 422 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
#operate between arrays
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [13]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])